config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  resources :sessions
  resources :users
  resources :events
  get 'logout', to: 'sessions#destroy', as: 'logout'
  root 'events#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
require 'date'

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, class_name: 'User', through: 'attendances'

  scope :upcoming_events, -> { where('date > ?', Date.today) }
  scope :previous_events, -> { where('date < ?', Date.today) }
  validates :title, presence: true
  validates :description, length: { in: (7...101) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id'
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, class_name: 'Event', through: :attendances

  validates :username, presence: true, length: { in: (4..11) }, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def create
    @event = current_user.attended_events.find_by_id(params[:attended_event_id])
    if @event.nil?
      @attendance = current_user.attendances.build(attended_event_id: params[:attended_event_id])
      if @attendance.save
        redirect_to root_path
      else
        redirect_to current_user
      end
    else
      redirect_to root_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[create new show]
  # before_action :authenticate_user, only: %i[create new show]
  def index
    @upcoming_events = Event.upcoming_events
    @previous_events = Event.previous_events
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to current_user
    else
      render 'new'
    end
  end

  def show
    @user = current_user
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  private

  def set_event
    redirect_to new_session_path if current_user.nil?
  end

  def event_params
    params.require(:event).permit(:date, :title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_username(params[:username])
    if user
      session[:user_id] = user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path flash[:success] = 'You have succesfully logged out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'user successfully created'
      redirect_to root_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def show
    @created_events = current_user.events
    @user = current_user
    @upcoming_events = current_user.attended_events.upcoming_events
    @previous_events = current_user.attended_events.previous_events
  end

  private

  def user_params
    params.require(:user).permit(:username, :userid, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f| %>
  <%= f.label :title, 'Event title' %> <br>
  <%= f.text_field :title, placeholder:'add an event date' %> <br>
  <%= f.label :date, 'Date' %> <br>
  <%= f.date_field :date, placeholder:'add an event date' %><br>
  <%= f.label :description, 'Description' %> <br>
  <%= f.text_field :description, size: "70x10" %><br>
  


  <%= f.submit 'create event'%><br>

<% end %>

app/views/events/index.html.erb
<div class="container">
  <div class="row col-md-12 justify-content-center">
    <h1 class="h1">events avaialable</h1>
    <%= render '/layouts/events' %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-6">
    <h2>create an event</h2>
   <%= render 'form' %> 
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-7">
      <%= @user.username %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-7">
      <h3>Attendee List</h3>
      <ul>
        <% @attendees.each do |attendee| %>
          <li><%= attendee.username %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_events.html.erb
<div class="container">
    
    <div class="row justify-content-center w-100">

    
        <h2 class="h2 text-center">Upcoming Events</h1>

      <% @upcoming_events.each do |event| %>
        <div class="card mb-3 col-md-4 mr-5">
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <p class="card-text"><%= event.date %></p>
            <p class="card-text"><%= event.description %></p>
            <p class="card-text">
              <span><%= link_to 'More Details', event %></span>
              <span><%= link_to 'Attend Event', attendances_path(:attended_event_id => event), method: :post %></span>
            </p>
          </div>
        </div>
      <% end %>

      
  </div>

    <div class="row justify-content-center w-100">

      <h2 class="h2 text-center">Previous Attended Events</h1>


      <% @previous_events.each do |event| %>
        <div class="card mb-3 col-md-4 mr-5">
          <div class="card-body">
            <h5 class="card-title"><%= event.title %></h5>
            <p class="card-text"><%= event.date %></p>
            <p class="card-text"><%= event.description %></p>
            <span><%= link_to 'More Details', event %></span>
            <span><%= link_to 'Attend Event', attendances_path(:attended_event_id => event), method: :post %></span>
          </div>
        </div>
      <% end %>

    </div>
  
</div>
  

app/views/layouts/_user_status.html.erb
<% if current_user %>
  <li><%= link_to "#{current_user.username}", current_user %></li>
  <li><%= link_to 'Sign Out', logout_path %></li>
  <li><%= link_to 'Create event', new_event_path  %></li>

<% else %>
  <li><%= link_to 'Sign In', new_session_path  %></li>
  <li><%= link_to 'Sign Up', new_user_path  %></li>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div>
        <h2><%= link_to 'Private Events', root_path  %></h2>
      </div>
      <div>
        <ul>
            <%= render '/layouts/user_status' %>            
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>create user</h1>

<%= form_for @user  do |f| %>
      <ul>
      <%if @user.errors.any?  %>
            <% @user.errors.full_messages.each do |msg| %>
            <li>
            <%=msg %>
            </li>
          <%end %>
      <% end %>
      </ul>
      <%= f.text_field :username, placeholder:'username'%>
      <%= f.text_field :email, placeholder:'your email'%>
      <%= f.submit 'sign Up' %>
<% end %>

app/views/users/show.html.erb
<div class="container">
    
    <div class="row justify-content-space-between w-100">

        <h2 class="h2"><%= @user.username %> created events</h1>


      <% @created_events.each do |event| %>
      <div class="card mb-3 col-md-4 mr-5">
      <div class="card-body">
        <h5 class="card-title"><%= event.title %></h5>
        <p class="card-text"><%= event.date %></p>
        <p class="card-text"><%= event.description %></p>
        <span><%= link_to 'More Details', event %></span>
              <span><%= link_to 'Attend Event', attendances_path(:attended_event_id => event), method: :post %></span>
      </div>
      </div>
      <% end %>


  </div>
    <div class="row justify-content-space-between w-100">

    
        <h2 class="h2">Upcoming Events</h1>

      <% @upcoming_events.each do |event| %>
      <div class="card mb-3 col-md-4 mr-5">
      <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <p class="card-text"><%= event.date %></p>
      <p class="card-text"><%= event.description %></p>
      <span><%= link_to 'More Details', event %></span>
              <span><%= link_to 'Attend Event', attendances_path(:attended_event_id => event), method: :post %></span>
      </div>
      </div>
      <% end %>

      
  </div>

    <div class="row justify-content-space-between w-100">

          <h2 class="h2">Previous Attended Events</h1>


      <% @previous_events.each do |event| %>
      <div class="card mb-3 col-md-4 mr-5">
      <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <p class="card-text"><%= event.date %></p>
      <p class="card-text"><%= event.description %></p>
      <span><%= link_to 'More Details', event %></span>
              <span><%= link_to 'Attend Event', attendances_path(:attended_event_id => event), method: :post %></span>
      </div>
      </div>
      <% end %>

    </div>
  
</div>
  